### ISSUE TITLE
No module named 'fs'

### ISSUE THREAD

**Issue by tallpauley** [goodhertz/coldtype#6]
On running coldtype in my virtual environment, I get `ModuleNotFoundError: No module named 'fs'`. 

See the following:
```bash

# double check I'm in the new venv I created just for Coldtype
$ echo $VIRTUAL_ENV
/Users/cmpauley/code/coldtype-example/env

# Check which packages are in this venv
$ pip list -l
pip list -l
Package                                           Version
------------------------------------------------- ------------
booleanOperations                                 0.9.0
coldtype                                          0.0.3
compreffor                                        0.5.0
cu2qu                                             1.6.7
defcon                                            0.7.2
drawBot                                           3.126
easing-functions                                  1.0.3
fontPens                                          0.2.4
fonttools                                         4.12.1
freetype-py                                       2.1.0.post1
install                                           1.3.1
mido                                              1.2.9
noise                                             1.2.2
numpy                                             1.19.0
pathtools                                         0.1.2
pip                                               19.2.3
pyclipper                                         1.1.0.post3
pyobjc                                            6.2.1
pyobjc-core                                       6.2.1
pyobjc-framework-Accounts                         6.2.1
pyobjc-framework-AddressBook                      6.2.1
pyobjc-framework-AdSupport                        6.2.1
pyobjc-framework-AppleScriptKit                   6.2.1
pyobjc-framework-AppleScriptObjC                  6.2.1
pyobjc-framework-ApplicationServices              6.2.1
pyobjc-framework-AuthenticationServices           6.2.1
pyobjc-framework-AutomaticAssessmentConfiguration 6.2.1
pyobjc-framework-Automator                        6.2.1
pyobjc-framework-AVFoundation                     6.2.1
pyobjc-framework-AVKit                            6.2.1
pyobjc-framework-BusinessChat                     6.2.1
pyobjc-framework-CalendarStore                    6.2.1
pyobjc-framework-CFNetwork                        6.2.1
pyobjc-framework-CloudKit                         6.2.1
pyobjc-framework-Cocoa                            6.2.1
pyobjc-framework-Collaboration                    6.2.1
pyobjc-framework-ColorSync                        6.2.1
pyobjc-framework-Contacts                         6.2.1
pyobjc-framework-ContactsUI                       6.2.1
pyobjc-framework-CoreAudio                        6.2.1
pyobjc-framework-CoreAudioKit                     6.2.1
pyobjc-framework-CoreBluetooth                    6.2.1
pyobjc-framework-CoreData                         6.2.1
pyobjc-framework-CoreHaptics                      6.2.1
pyobjc-framework-CoreLocation                     6.2.1
pyobjc-framework-CoreMedia                        6.2.1
pyobjc-framework-CoreMediaIO                      6.2.1
pyobjc-framework-CoreML                           6.2.1
pyobjc-framework-CoreMotion                       6.2.1
pyobjc-framework-CoreServices                     6.2.1
pyobjc-framework-CoreSpotlight                    6.2.1
pyobjc-framework-CoreText                         6.2.1
pyobjc-framework-CoreWLAN                         6.2.1
pyobjc-framework-CryptoTokenKit                   6.2.1
pyobjc-framework-DeviceCheck                      6.2.1
pyobjc-framework-DictionaryServices               6.2.1
pyobjc-framework-DiscRecording                    6.2.1
pyobjc-framework-DiscRecordingUI                  6.2.1
pyobjc-framework-DiskArbitration                  6.2.1
pyobjc-framework-DVDPlayback                      6.2.1
pyobjc-framework-EventKit                         6.2.1
pyobjc-framework-ExceptionHandling                6.2.1
pyobjc-framework-ExecutionPolicy                  6.2.1
pyobjc-framework-ExternalAccessory                6.2.1
pyobjc-framework-FileProvider                     6.2.1
pyobjc-framework-FileProviderUI                   6.2.1
pyobjc-framework-FinderSync                       6.2.1
pyobjc-framework-FSEvents                         6.2.1
pyobjc-framework-GameCenter                       6.2.1
pyobjc-framework-GameController                   6.2.1
pyobjc-framework-GameKit                          6.2.1
pyobjc-framework-GameplayKit                      6.2.1
pyobjc-framework-ImageCaptureCore                 6.2.1
pyobjc-framework-IMServicePlugIn                  6.2.1
pyobjc-framework-InputMethodKit                   6.2.1
pyobjc-framework-InstallerPlugins                 6.2.1
pyobjc-framework-InstantMessage                   6.2.1
pyobjc-framework-Intents                          6.2.1
pyobjc-framework-IOSurface                        6.2.1
pyobjc-framework-iTunesLibrary                    6.2.1
pyobjc-framework-LatentSemanticMapping            6.2.1
pyobjc-framework-LaunchServices                   6.2.1
pyobjc-framework-libdispatch                      6.2.1
pyobjc-framework-LinkPresentation                 6.2.1
pyobjc-framework-LocalAuthentication              6.2.1
pyobjc-framework-MapKit                           6.2.1
pyobjc-framework-MediaAccessibility               6.2.1
pyobjc-framework-MediaLibrary                     6.2.1
pyobjc-framework-MediaPlayer                      6.2.1
pyobjc-framework-MediaToolbox                     6.2.1
pyobjc-framework-Metal                            6.2.1
pyobjc-framework-MetalKit                         6.2.1
pyobjc-framework-ModelIO                          6.2.1
pyobjc-framework-MultipeerConnectivity            6.2.1
pyobjc-framework-NaturalLanguage                  6.2.1
pyobjc-framework-NetFS                            6.2.1
pyobjc-framework-Network                          6.2.1
pyobjc-framework-NetworkExtension                 6.2.1
pyobjc-framework-NotificationCenter               6.2.1
pyobjc-framework-OpenDirectory                    6.2.1
pyobjc-framework-OSAKit                           6.2.1
pyobjc-framework-OSLog                            6.2.1
pyobjc-framework-PencilKit                        6.2.1
pyobjc-framework-Photos                           6.2.1
pyobjc-framework-PhotosUI                         6.2.1
pyobjc-framework-PreferencePanes                  6.2.1
pyobjc-framework-PushKit                          6.2.1
pyobjc-framework-Quartz                           6.2.1
pyobjc-framework-QuickLookThumbnailing            6.2.1
pyobjc-framework-SafariServices                   6.2.1
pyobjc-framework-SceneKit                         6.2.1
pyobjc-framework-ScreenSaver                      6.2.1
pyobjc-framework-ScriptingBridge                  6.2.1
pyobjc-framework-SearchKit                        6.2.1
pyobjc-framework-Security                         6.2.1
pyobjc-framework-SecurityFoundation               6.2.1
pyobjc-framework-SecurityInterface                6.2.1
pyobjc-framework-ServiceManagement                6.2.1
pyobjc-framework-Social                           6.2.1
pyobjc-framework-SoundAnalysis                    6.2.1
pyobjc-framework-Speech                           6.2.1
pyobjc-framework-SpriteKit                        6.2.1
pyobjc-framework-StoreKit                         6.2.1
pyobjc-framework-SyncServices                     6.2.1
pyobjc-framework-SystemConfiguration              6.2.1
pyobjc-framework-SystemExtensions                 6.2.1
pyobjc-framework-UserNotifications                6.2.1
pyobjc-framework-VideoSubscriberAccount           6.2.1
pyobjc-framework-VideoToolbox                     6.2.1
pyobjc-framework-Vision                           6.2.1
pyobjc-framework-WebKit                           6.2.1
python-bidi                                       0.4.2
setuptools                                        41.2.0
six                                               1.15.0
skia-pathops                                      0.4.1
ufo2ft                                            2.15.0
uharfbuzz                                         0.12.0
unicodedata2                                      13.0.0.post2
watchdog                                          0.10.2
websocket-client                                  0.57.0
websockets                                        8.1

# Try coldtype
$ coldtype
Traceback (most recent call last):
  File "/Users/cmpauley/code/coldtype-example/env/bin/coldtype", line 6, in <module>
    from coldtype.renderer import main
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/coldtype/__init__.py", line 4, in <module>
    from coldtype.text import *
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/coldtype/text/__init__.py", line 1, in <module>
    from coldtype.text.reader import Style, StyledString, SegmentedString, normalize_font_path, Font, FontNotFoundException
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/coldtype/text/reader.py", line 13, in <module>
    from coldtype.pens.datpen import DATPen, DATPenSet
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/coldtype/pens/datpen.py", line 17, in <module>
    from defcon import Glyph
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/defcon/__init__.py", line 10, in <module>
    from defcon.objects.font import Font
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/defcon/objects/font.py", line 6, in <module>
    from fontTools.ufoLib import UFOReader, UFOWriter, UFOLibError, UFOFileStructure, UFOFormatVersion
  File "/Users/cmpauley/code/coldtype-example/env/lib/python3.7/site-packages/fontTools/ufoLib/__init__.py", line 8, in <module>
    import fs
ModuleNotFoundError: No module named 'fs'
```

EDIT: I first was using VSCode console, so `coldtype` was reporting it couldn't find module `fs`, but `pip list -l` was showing `fs` in the listing. Using iTerm2 we can see that the module actually isn't there (as expected). VSCode terminal does something magic with one of the plugins I have, automatically going into the virtualenv and what not.

**Comment by tallpauley** [comment]
Ok, @stenson solved this one. Here is what happened:

1. Github's markdown is rendering your `pip` installation steps in your README as one line. [See relevant GFM spec here](https://github.github.com/gfm/#block-quotes)
2. I copied this line straight into my terminal like a dummy: `pip install coldtype[renderer] pip install git+https://github.com/typemytype/drawbot`
3. Pip happily tries to install`coldtype[renderer]`, `pip`, `install`, and `git+https://github.com/typemytype/drawbot`
4. But `fs` is missing, why?? Turns out its some weird package ordering thing. If I do `pip install git+https://github.com/typemytype/drawbot coldtype[renderer]` I get the same issue. For some reason you can't install them both at once— they have to be installed in the order you mention. And it seems that pip doesn't pay attention to the order if you list multiple packages in a `pip install` command.
5. So, I guess the solution is just putting a newline between the lines of terminal commands? Would have just made a pull request, but wondered if you have a reason for using blockquotes for command-line stuff vs. code blocks?

**Comment by stenson** [comment]
This was a result of trying to modularize some of the dependencies; now all the required dependencies are part of the base requirement set, so coldtype should now install correctly with just a `pip install coldtype`, no brackets required
